AllCops:
  Exclude:
    - 'tmp/**/*'

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'features/step_definitions/**/*'

Metrics/MethodLength:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    find: 'detect'
    reduce: 'inject'

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/RegexpLiteral:
  MaxSlashes: 0

Style/SymbolArray:
  Enabled: true
