name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - id: meta
        name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: thoughtbot/paperback

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: arm64,amd64
